import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { JSDOM } from 'jsdom';
import { mountBoard } from '../js/progress-board.js';
const PAGE = await readFile(new URL('../control-room.html', import.meta.url), 'utf8');
const task = {id:'demo', title:'Demo job', stage:'build', summary:'Demo summary', model:'gpt-6-sol', effort:'high'};
const read = {snapshot:{board_id:'project',version:1,snapshot_json:{title:'Demo',tasks:{demo:task}}},questions:[]};
test('merged renderer mounts in Control Room and keeps card popup and governance originals', async () => {
 const dom = new JSDOM(PAGE, {url:'https://example.test/control-room/progress?board=project'});
 const opened=[];
 const board=mountBoard({window:dom.window, document:dom.window.document, client:{readProgressBoard:async()=>read}, openTask:row=>opened.push(row), storage:null, setInterval:()=>0, setTimeout:()=>0, clearTimeout:()=>{}});
 await board.refresh();
 assert.equal(dom.window.document.querySelector("#board-title").textContent,"System Job Board");
 assert.equal(dom.window.document.title,"Control Room · DoctorCRE");
 const card=dom.window.document.querySelector('.board-card');card.click();
 assert.equal(opened[0].id,'demo');assert.equal(opened[0].summary,'Demo summary');
 const queue={ok:true,counts:{total:1,pending_rule_approvals:1,pending_guidance_import_batches:0,pending_retrieval_proposals:0},pending_rule_approvals:[{rule_id:'demo-rule',statement:'Demo original',status:'proposed',taught_at:'2026-10-02T12:00:00Z'}],pending_guidance_import_batches:[],pending_retrieval_proposals:[]};
 board.setGovernance(queue);
 const approval=dom.window.document.querySelector('[data-task-id^="governance:"]');assert.ok(approval);approval.click();assert.equal(opened[1].governance.entry.statement,'Demo original');
 board.setGovernance(null,{reason:'Unavailable'});assert.match(dom.window.document.querySelector('#governanceState').textContent,/last-known/);
 board.dispose();dom.window.close();
});
